import { NextResponse, type NextRequest } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase-server'
import { logger } from '@/lib/logger'

// ── Reçoit le code OAuth Google, échange en tokens, stocke dans Supabase ─────
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const code = searchParams.get('code')
  const state = searchParams.get('state') // = syndic_id:nonce
  const error = searchParams.get('error')

  const APP_URL = process.env.NEXT_PUBLIC_APP_URL || ''

  if (error || !code || !state) {
    return NextResponse.redirect(`${APP_URL}/syndic/dashboard?email_error=${error || 'missing_code'}`)
  }

  // CSRF: state = syndic_id:nonce — extract and verify
  const stateParts = state.split(':')
  const syndicId = stateParts[0]
  const nonce = stateParts[1]

  if (!syndicId || !/^[0-9a-f-]{36}$/i.test(syndicId) || !nonce) {
    return NextResponse.redirect(`${APP_URL}/syndic/dashboard?email_error=invalid_state`)
  }

  // ── Verify the nonce was generated by our connect route ──
  const { data: tokenRow } = await supabaseAdmin
    .from('syndic_oauth_tokens')
    .select('oauth_nonce, oauth_nonce_expires_at')
    .eq('syndic_id', syndicId)
    .single()

  if (!tokenRow?.oauth_nonce || tokenRow.oauth_nonce !== nonce) {
    logger.error('OAuth CSRF: nonce mismatch for syndic', syndicId)
    return NextResponse.redirect(`${APP_URL}/syndic/dashboard?email_error=csrf_failed`)
  }

  // Check nonce expiry (10 min window)
  if (tokenRow.oauth_nonce_expires_at && new Date(tokenRow.oauth_nonce_expires_at) < new Date()) {
    logger.error('OAuth CSRF: nonce expired for syndic', syndicId)
    return NextResponse.redirect(`${APP_URL}/syndic/dashboard?email_error=state_expired`)
  }

  const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID!
  const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET!

  try {
    // 1. Échanger le code contre des tokens
    const tokenRes = await fetch('https://oauth2.googleapis.com/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        code,
        client_id: GOOGLE_CLIENT_ID,
        client_secret: GOOGLE_CLIENT_SECRET,
        redirect_uri: `${APP_URL}/api/email-agent/callback`,
        grant_type: 'authorization_code',
      }),
    })

    const tokenData = await tokenRes.json()

    if (!tokenRes.ok || !tokenData.access_token) {
      logger.error('Token exchange error:', tokenData)
      return NextResponse.redirect(`${APP_URL}/syndic/dashboard?email_error=token_exchange`)
    }

    // 2. Récupérer l'email du compte Gmail connecté
    const profileRes = await fetch('https://www.googleapis.com/oauth2/v2/userinfo', {
      headers: { Authorization: `Bearer ${tokenData.access_token}` },
    })
    const profile = await profileRes.json()
    const emailCompte = profile.email || 'Inconnu'

    // 3. Calculer l'expiration du token
    const tokenExpiry = new Date(Date.now() + (tokenData.expires_in || 3600) * 1000).toISOString()

    // 4. Stocker les tokens dans Supabase (upsert) + clear nonce (prevent replay)
    const { error: upsertError } = await supabaseAdmin
      .from('syndic_oauth_tokens')
      .upsert({
        syndic_id: syndicId,
        provider: 'gmail',
        access_token: tokenData.access_token,
        refresh_token: tokenData.refresh_token || '',
        token_expiry: tokenExpiry,
        email_compte: emailCompte,
        scope: tokenData.scope || '',
        oauth_nonce: null,
        oauth_nonce_expires_at: null,
        updated_at: new Date().toISOString(),
      }, { onConflict: 'syndic_id' })

    if (upsertError) {
      logger.error('Supabase upsert error:', upsertError)
      return NextResponse.redirect(`${APP_URL}/syndic/dashboard?email_error=db_error`)
    }

    // 5. Lancer une première analyse immédiate (via cron key pour auth interne)
    const cronSecret = process.env.CRON_SECRET
    if (cronSecret) {
      fetch(`${APP_URL}/api/email-agent/poll`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-cron-key': cronSecret,
        },
        body: JSON.stringify({ first_run: true }),
      }).catch(err => logger.error('[email-agent/callback] Fire-and-forget poll failed:', err))
    }

    return NextResponse.redirect(`${APP_URL}/syndic/dashboard?email_connected=true&email=${encodeURIComponent(emailCompte)}`)

  } catch (err: unknown) {
    logger.error('[email-agent/callback] OAuth error:', err)
    return NextResponse.redirect(`${APP_URL}/syndic/dashboard?email_error=server_error`)
  }
}
